version: '3.4'

services:
  pdfcompare:
    build:
      context: .
      network: host
    container_name: daps
    hostname: daps
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: .
        target: /home/user
    entrypoint: pdfcompare
